### ISSUE TITLE
try learning rates from "GANs Trained by a Two Time-Scale Update Rule Converge to a Nash Equilibrium": https://arxiv.org/abs/1706.08500

### ISSUE THREAD

**Issue by ethancaballero** [AlexiaJM/Deep-learning-with-cats#1]
source code:
https://github.com/bioinf-jku/TTUR/blob/ca9b6572d08f81d0725de8558400fb17585266d3/WGAN_GP/gan_64x64_FID.py#L45-L49

**Comment by AlexiaJM** [comment]
I wish someone could implement their Fréchet Inception Distance in PyTorch, it's what I'm most interested in but nobody even implemented the basic Inception Distance yet in Pytorch.

If I understood correctly, the TTUR is mostly just a theoretical proof that tweaking the learning rates for G and D (not forcing them equal) will lead eventually to a sweet spot (nash equilibrium) which seems to be pretty much what I did with DCGAN. For WGAN-GP, you can set --n_critic 1 and experiment with different lr_D and lr_G to see if you can get better results.
