### ISSUE TITLE
Cat DataSet

### ISSUE THREAD

**Issue by world4jason** [AlexiaJM/Deep-learning-with-cats#12]
the link to cat dataset returns "503 service unavailable"

**Comment by AlexiaJM** [comment]
I tried twice, once I got 503 error and the other time not, so try a couple of times. Btw, in "Setting up the data/setting_up_script.sh" it will automatically download the dataset. If nothing works, get it here by torrent: http://academictorrents.com/details/c501571c29d16d7f41d159d699d0e7fb37092cbd.

**Comment by Thomasasia** [comment]
Thanks a bunch!
