### ISSUE TITLE
Question about WGAN

### ISSUE THREAD

**Issue by AceCoooool** [AlexiaJM/Deep-learning-with-cats#18]
I am confusing about the code in training Discriminator phase:  
```
errD_real = D(x)
errD_real.backward(one)
...
errD_fake = D(x_fake)
errD_fake.backward(one_neg)
```
But D is $maxV(G,D)=E(D(real))-E(D(fake))$ , i think in “loss form” is inverse
```
errD_real = D(x)
errD_real.backward(one_neg)
...
errD_fake = D(x_fake)
errD_fake.backward(one)
```

**Comment by AlexiaJM** [comment]
Yes, it's inverted. I fixed it in https://github.com/AlexiaJM/RelativisticGAN. It doesn't change anything though, D(fake) just go small and D(x_real) big instead of the opposite.
