### ISSUE TITLE
What would be interesting to see is for each cat the training example closest to it

### ISSUE THREAD

**Issue by kootenpv** [AlexiaJM/Deep-learning-with-cats#2]
Maybe you could do a simple unweighted average pixel difference over the dataset for the example cats and see if it is not just overfitting on the training data?
I would almost say they don't look distorted enough to be really generated :)

**Comment by AlexiaJM** [comment]
I'm also missing a way to generate more than the same cats once the model is trained. I'm not sure how to best set these ideas though. What about adding two arguments:
1) posthoc_generate_N_batchs (Default=0) How many additional images of fake cats to generate (assuming an already trained model)
1) posthoc_most_similar_cats (Default=1) For the additional images generated from posthoc_generate_N_batchs, also show the k most similar cats from the training dataset. k is the parameter here.

**Comment by AlexiaJM** [comment]
https://github.com/AlexiaJM/Generative-model-most-similar-images
