### ISSUE TITLE
dataset download failed

### ISSUE THREAD

**Issue by tak-wah** [AlexiaJM/Deep-learning-with-cats#4]
the Cat Dataset (https://web.archive.org/web/20150703060412/http://137.189.35.203/WebUI/CatDatabase/catData.html)
unable to download.

**Comment by AlexiaJM** [comment]
Luckily, you can get it here if the web archive doesn't work: http://academictorrents.com/details/c501571c29d16d7f41d159d699d0e7fb37092cbd. I haven't tried it but I assume it's the same.
